version: '3.8'

services:

  backend:
    image: backendimage
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    image: frontendimage
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
